# .github/workflows/update-codey.yml
name: Update Codey

on:
  schedule:
    - cron: '0 6 * * *'  # Täglich 6:00
  workflow_dispatch:

jobs:
  update-codey:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install requests
        fi

    - name: Update Codey
      run: python update_codey.py
      env:
        # benutze das automatisch verfügbare Token (empfohlen)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Falls du weiterhin ein eigenes Secret verwenden willst, füge es zu den Repo-Secrets hinzu
        # GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Commit
      run: |
        git config --local user.name "Codey Bot"
        git config --local user.email "action@github.com"
        git add codey.svg codey.json
        git commit -m "🐾 Daily Codey update" || exit 0
        git push
