name: Update Codey
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-codey:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        # entweder entferne die token-Zeile ganz (dann wird GITHUB_TOKEN genutzt),
        # oder explizit GITHUB_TOKEN setzen:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi

    - name: Update Codey
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # optional fallback, nur wenn du ein PAT verwenden willst:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIT_REPOSITORY: ${{ vars.GIT_REPOSITORY }}
      run: python update_codey.py

    - name: Commit
      run: |
        git config --local user.name "Codey Bot"
        git config --local user.email "action@github.com"
        git add codey.svg codey.json
        git commit -m "🐾 Daily Codey update" || exit 0
        git push
